version: '3'

services:
    php:
        links:
            - mysql
            - psql
            - elasticsearch
            - cache
    elasticsearch:
        image: elasticsearch:6.6.0
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
        volumes:
            - ./docker/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            app_net:
               ipv4_address: 10.1.0.105 
