#!/bin/sh

NAME=schedule
DESC="Schedule daemon"
PIDFILE="/tmp/${NAME}.pid"
LOGFILE="/tmp/${NAME}.log"

DAEMON="/bin/bash"
DAEMON_OPTS="/usr/local/bin/php-entrypoint.sh"

START_OPTS="--start --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} ${DAEMON_OPTS}"
STOP_OPTS="--stop --pidfile ${PIDFILE}"

test -x $DAEMON || exit 0

set -e

if [ ! -f $LOGFILE ]; then
    touch $LOGFILE
    chown 1000:1000 $LOGFILE
fi

if [ ! -f $PIDFILE ]; then
    touch $PIDFILE
    chown 1000:1000 $PIDFILE
fi

case "$1" in
start)
echo -n "Starting ${DESC}: "


start-stop-daemon $START_OPTS >> $LOGFILE
echo "$NAME."
;;
stop)
echo -n "Stopping $DESC: "
start-stop-daemon $STOP_OPTS
echo "$NAME."
rm -f $PIDFILE
;;
restart|force-reload)
echo -n "Restarting $DESC: "
start-stop-daemon $STOP_OPTS
sleep 1

start-stop-daemon $START_OPTS >> $LOGFILE
echo "$NAME."
;;
*)
N=/etc/init.d/$NAME
echo "Usage: $N {start|stop|restart|force-reload}" >&2
exit 1
;;
esac

exit 0
